# -*- coding: utf-8 -*-
"""Analise_exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qtm0-hIBHYOGroYeA7BQLtapgHMVkPhG
"""

# importando as bibliotecas
import pandas as pd
import matplotlib.pyplot as plt

# Criando o dataframe
df = pd.read_excel("/content/drive/MyDrive/datasets/AdventureWorks.xlsx")

df.head()

# Quantidade de linhas e colunas
df.shape

# Verificando os tipos de dados
df.dtypes

# Qual a receita total?
df["Valor Venda"].sum()

# Qual o custo total?
# Precisamos criar uma coluna de custo primeiramente, ja que só temos o custo unitário, portanto, custo unitario * quantidade
df["Custo"] = df["Custo Unitário"].mul(df['Quantidade'])

df.head(1)

# Agora que temos a row custo, podemos visualizar o custo total
round(df["Custo"]. sum(), 2)

# Agora que temos a receita e custo total, podemos achar o Lucro
# Criamos uma row Lucro que será REceita - Custo
df["Lucro"] = df["Valor Venda"] - df["Custo"]

df.head(2)

# Total Lucro
round(df["Lucro"].sum(), 2)

# Criando uma row com o total de dias para enviar o produto
df["Tempo_envio"] = df["Data Envio"] - df["Data Venda"]

df.head(1)

# Extraindo apenas os dias
df["Tempo_envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df.head(1)

# Agora que temos só os dias podemos achar a MÉDIA do tempo de envio
df.groupby("Marca")["Tempo_envio"].mean()

# Verificando se temops dados faltantes
df.isnull().sum()

# Agrupando por ano e marca
df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

# remodelando a informação 
pd.options.display.float_format = '{:20,.2f}'.format

# Resetando o index - Fazendo com que a ultima informação fique em sentido de tabela
lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum().reset_index()
lucro_ano

# Qual o total de produtos vendidos?
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

# Gráfico total de produtos vendidos
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

# Gráfico de lucro por x ano
df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title="Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

# Selecionando as vendas de 2019
df_2009 = df[df["Data Venda"].dt.year == 2009]

df_2009

# Visualizando lucros por mes em 2019
df_2009.groupby(df_2009["Data Venda"].dt.month)["Lucro"].sum().plot(title="Lucro x Mes")
plt.xlabel("Mês")
plt.ylabel("Lucro");

df_2009.groupby("Marca")["Lucro"].sum().plot.bar(title="Lucro x Marca")
plt.xlabel("Mês")
plt.ylabel("Lucro");
plt.xticks(rotation='horizontal');

df["Tempo_envio"].describe()

# Gráfico em boxplot
plt.boxplot(df["Tempo_envio"]);

# Gráfico em histograma
plt.hist(df["Tempo_envio"]);

