# -*- coding: utf-8 -*-
"""projeto_dio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lhQfdFEDJjerkyqWScxi-NYI5V3NYm4k
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/datasets/Gapminder.csv", error_bad_lines=False, sep=";")

# Visualizando as cinco primeiras linhas
df.head()

# Renomeando o header para português
df = df.rename(columns={"country": "Pais", "continent": "Continente", "year": "Ano", "lifeExp": "Expectativa de Vida", "pop": "Pop Total", "gdpPercap": "PIB"})

df.head(10)

# Por informação, queremos saber o total de linhas e colunas
df.shape

df.columns

df.dtypes

# Visualizando as ultimas linhas
df.tail(10)

# Visualizando informações estatísticas do nosso conjunto de dados
df.describe()

df["Continente"].unique()

# Atribuindo a variável oceania somente a chave "Continente" que tiver o valor "Oceania"
oceania = df.loc[df["Continente"] == "Oceania"] 
oceania.head(10)

df.groupby("Continente")["Pais"].nunique()

# Descobrindo qual expectativa de vida para cada ano único
df.groupby("Ano")["Expectativa de Vida"].mean()

df["PIB"].mean()

